version = 0.1
[default.deploy.parameters]
stack_name = "livestream-app"
resolve_s3 = true
s3_prefix = "livestream-app"
region = "us-east-1"
profile = "gutkedu-terraform"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Env=\"dev\""
image_repositories = []
