AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Main Stack

Parameters:
  Env:
    Type: String
    Default: dev
    Description: Environment name (e.g., dev, prod)
    AllowedValues:
      - dev
      - prod
  
  MomentoCacheApiKey:
    Type: String
    NoEcho: true
    Description: API Key for Momento Cache

Resources:   
  BackendStackApplication:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./backend/template.yaml
      Parameters:
        Env: !Ref Env

  SharedResourcesApplication:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./shared/template.yaml
      Parameters:
        Env: !Ref Env
        MomentoCacheApiKey: !Ref MomentoCacheApiKey

Outputs:  
  ApiGatewayURL:
    Description: URL for the API Gateway
    Value: !GetAtt BackendStackApplication.Outputs.ApiGatewayURL