version = 0.1
[default.deploy.parameters]
stack_name = "hackaton-stateless-resources"
resolve_s3 = true
s3_prefix = "hackaton-stateless-resources"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "AppName=\"ServerlessHackaton\""
image_repositories = []
