version = 0.1
[default.deploy.parameters]
stack_name = "hackaton-stateless-resources"
resolve_s3 = true
s3_prefix = "hackaton-stateless-resources"
region = "us-east-1"
profile = "gutkedu-terraform"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "AppName=\"LivestreamApp\" ContainerImageUri=\"396608768142.dkr.ecr.us-east-1.amazonaws.com/hackaton-container-app:latest\""
image_repositories = []
