AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Stateless Resources Stack

Parameters:
  AppName:
    Type: String
    Default: ServerlessHackaton
    
  ContainerImageUri:
    Type: String
    Description: URI for the container image in ECR

Resources:   
  BackendStackApplication:
    Type: AWS::Serverless::Application
    Properties:
      Location: ../../code/backend/template.yaml
      Parameters:
        TableName: !ImportValue "StatefulStack-TableName"
        UserPoolId: !ImportValue "StatefulStack-UserPoolId"
        UserPoolClientId: !ImportValue "StatefulStack-UserPoolClientId"

Outputs:  
  ApiGatewayURL:
    Description: URL for the API Gateway
    Value: !GetAtt BackendStackApplication.Outputs.ApiGatewayURL
    
  ContainerProxyURL:
    Description: URL for the Container Proxy API
    Value: !GetAtt ContainerStackApplication.Outputs.ContainerProxyURL
