version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - USER_POOL_ID=${USER_POOL_ID}
      - USER_POOL_CLIENT_ID=${USER_POOL_CLIENT_ID}
      - TABLE_NAME=${TABLE_NAME}
    volumes:
      - ./src:/app/src
