version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - USER_POOL_ID=${USER_POOL_ID:-local-user-pool-id}
      - USER_POOL_CLIENT_ID=${USER_POOL_CLIENT_ID:-local-user-pool-client-id}
      - TABLE_NAME=${TABLE_NAME:-local-table-name}
    volumes:
      - ./src:/app/src
