AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB Table with Partition Key and Sort Key

Parameters:
  TableName:
    Type: String
    Description: Name of the DynamoDB table
    
Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: gsi1pk
          AttributeType: S
        - AttributeName: gsi1sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: gsi1
          KeySchema:
            - AttributeName: gsi1pk
              KeyType: HASH
            - AttributeName: gsi1sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Name
          Value: !Ref TableName

Outputs:
  TableName:
    Description: Name of the DynamoDB table
    Value: !Ref DynamoDBTable
  
  TableArn:
    Description: ARN of the DynamoDB table
    Value: !GetAtt DynamoDBTable.Arn