version = 0.1
[default.deploy.parameters]
stack_name = "hackaton-stateful-resources"
resolve_s3 = true
s3_prefix = "hackaton-stateful-resources"
region = "us-east-1"
profile = "gutkedu-terraform"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "MomentoCacheApiKey=\"your-api-key-here\""
image_repositories = []
