@url={{baseUrl}}
@contentType = application/json
@authToken = {{signin.response.body.accessToken}}
@idToken = {{signin.response.body.idToken}}

### Sign in to get token
# @name signin
POST {{url}}/auth/signin
Content-Type: application/json

{
  "email": "vaboxe9310@harinv.com",
  "password": "Senha123!"
}

### Get Topics Token
GET {{url}}/auth/topics-token?topic=lobby
Authorization: {{idToken}}

### Sign Up
POST {{url}}/auth/signup
Content-Type: application/json

{
  "email": "vaboxe9310@harinv.com",
  "password": "Senha123!",
  "username": "vaboxe9310"
}

### Confirm Sign Up
POST {{url}}/auth/confirm-signup
Content-Type: application/json

{
  "email": "vaboxe9310@harinv.com",
  "confirmationCode": "572198"
}


### Refresh Token
POST {{url}}/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiUlNBLU9BRVAifQ.c4c1CcXdjhllzGzXV-4A_kGsMElzKndRPn3GPuGgFhpuV2NaEml2c7GnXBF59pxP6m0yq9pNO7dZxNWt4xmf8Fuet2kw9zDz9DdYGBg6twuJ7_7prC[...]"
}

### Forgot Password
POST {{url}}/auth/forgot-password
Content-Type: application/json

{
  "email": "user@example.com"
}

### Reset Password
POST {{url}}/auth/reset-password
Content-Type: application/json

{
  "email": "user@example.com",
  "confirmationCode": "708886",
  "newPassword": "Password123!"
}