@url={{baseUrl}}
@contentType = application/json
@accessToken = {{signin.response.body.accessToken}}
@idToken = {{signin.response.body.idToken}}

### Sign in to get token
# @name signin
POST {{url}}/auth/signin
Content-Type: {{contentType}}

{
  "email": "vaboxe9310@harinv.com",
  "password": "Senha123!"
}


### List all lobbies
GET {{url}}/game/lobbies
Authorization: Bearer {{idToken}}


### Get lobby details
GET {{url}}/game/lobbies/2wePmhojsFEwdYPxEIyWg3zqPQK
Authorization: Bearer {{idToken}}

### Join lobby
POST {{url}}/game/lobbies/join
Content-Type: {{contentType}}
Authorization: Bearer {{idToken}}

{
  "lobbyId": "2NqvDLzdg5ThbAk6enzMrbtMq8S"
}

### Create new lobby
POST {{url}}/game/lobbies/create
Content-Type: {{contentType}}
Authorization: {{idToken}}

{
  "name": "Test Lobby",
  "maxPlayers": 4
}

### Start game in lobby
POST {{url}}/game/lobbies/start
Content-Type: {{contentType}}
Authorization: Bearer {{idToken}}

{
  "lobbyId": "2wztEXbZUuN3ZFMbBiXqLw49yLg",
  "difficulty": "medium"
}

### Leave lobby
POST {{url}}/game/lobbies/leave
Content-Type: {{contentType}}
Authorization: {{idToken}}

{}
