@url={{baseUrl}}
@contentType = application/json
@accessToken = {{signin.response.body.accessToken}}
@idToken = {{signin.response.body.idToken}}

### Sign in to get token
# @name signin
POST {{url}}/auth/signin
Content-Type: {{contentType}}

{
  "email": "vaboxe9310@harinv.com",
  "password": "Senha123!"
}


### List all lobbies
GET {{url}}/game/lobbies
Authorization: Bearer {{idToken}}


### Get lobby details
GET {{url}}/game/lobbies/2wePmhojsFEwdYPxEIyWg3zqPQK
Authorization: Bearer {{idToken}}

### Join lobby
POST {{url}}/game/lobbies/join
Content-Type: {{contentType}}
Authorization: Bearer {{idToken}}

{
  "lobbyId": "2NqvDLzdg5ThbAk6enzMrbtMq8S"
}

### Create new lobby
POST {{url}}/game/lobbies/create
Content-Type: {{contentType}}
Authorization: Bearer {{idToken}}

{
  "name": "Test Lobby",
  "maxPlayers": 4
}

### Start game in lobby
POST {{url}}/game/lobbies/start
Content-Type: {{contentType}}
Authorization: Bearer {{idToken}}

{
  "lobbyId": "2xCf80nIdnid0CGoG2gFR5ZCWnC",
  "difficulty": "medium"
}

### Return to previously joined lobby
POST {{url}}/game/lobbies/return
Content-Type: {{contentType}}
Authorization: Bearer {{idToken}}

{
  "lobbyId": "2xCf80nIdnid0CGoG2gFR5ZCWnC",
  "difficulty": "medium"
}

### Leave lobby
POST {{url}}/game/lobbies/leave
Content-Type: {{contentType}}
Authorization: Bearer {{idToken}}

{}


### Return to lobby (useful after game ended)
POST {{url}}/game/lobbies/return
Content-Type: {{contentType}}
Authorization: Bearer {{idToken}}

{
  "lobbyId": "2xCf80nIdnid0CGoG2gFR5ZCWnC"
}


### Select user state
GET {{url}}/game/me
Authorization: Bearer {{idToken}}


### End Game
POST {{url}}/game/end
Content-Type: {{contentType}}
Authorization: Bearer {{idToken}}

{
  "lobbyId": "2xGkpzozGwqZJSNWtyfBAe57vxs",
  "players": [
    {
      "username": "vaboxe9310",
      "wpm": 100,
      "progress": 0.5
    }
  ]
}


### Game statistics
GET {{url}}/game/statistics
Authorization: Bearer {{idToken}}