@url={{baseUrl}}
@urlContainer={{baseUrlContainer}}
@contentType = application/json
@accessToken = {{signin.response.body.accessToken}}

### Sign in to get token
# @name signin
POST {{url}}/auth/signin
Content-Type: application/json

{
  "email": "vaboxe9310@harinv.com",
  "password": "Senha123!"
}

### Hello
GET {{urlContainer}}/hello


### Health Check
GET {{urlContainer}}/health

### Protected test
GET {{urlContainer}}/protected
Authorization: Bearer {{accessToken}}