name: Backend Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'code/backend/**'
      - 'stacks/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'code/backend/**'
      - 'stacks/**'

env:
  AWS_REGION: us-east-1
  SAM_CLI_TELEMETRY: 0

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: code/backend/package-lock.json

      - name: Install dependencies
        working-directory: code/backend
        run: npm ci
      
      - name: check build
        working-directory: code/backend
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Stateful Resources
        if: github.ref == 'refs/heads/main'
        working-directory: stacks/stateful
        run: |
          sam build && \
          sam deploy \
            --parameter-overrides "MomentoCacheApiKey=${{ secrets.MOMENTO_CACHE_API_KEY }}" \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \

      - name: Deploy Stateless Resources
        if: github.ref == 'refs/heads/main'
        working-directory: stacks/stateless
        run: |
          sam build && \
          sam deploy \
            --parameter-overrides "AppName=\"ServerlessHackaton\"" \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \